### ISSUE TITLE
Progressive Project Updates

### ISSUE THREAD

**Issue by Dihfahsih1** [Tanga-Jonathan/sukinome#1]
### What would you like to share?

Hello Tanga,

Thanks for the new updates on your project,
As you are aware, we are racing against time towards the end of the course.
Please ensure that you expedite your project progress by hastily adding more css, bootstrap classes and more HTML elements to make your project more presentable at the end of the course.

Thanks 

### Additional information

If possible you can add in some php code that you have mastered

**Comment by Tanga-Jonathan** [comment]
Thank you Sir, for taking us through containers in Bootstrap that was my disease 😔, I have tried to update my work, but more better work os coming
